services:
  userrpc:
    image: user:v1
    container_name: micro-user-rpc
    restart: always
    networks:
      - micro-mall

  entrpc:
    image: ent:v1
    container_name: micro-ent-rpc
    restart: always
    networks:
      - micro-mall

  entrpc2:
    image: ent:v1
    container_name: micro-ent-rpc2
    restart: always
    networks:
      - micro-mall

  entrpc3:
    image: ent:v1
    container_name: micro-ent-rpc3
    restart: always
    networks:
      - micro-mall

  userapi:
    image: userapi:v1
    restart: always
    container_name: micro-user-api
    networks:
      - micro-mall
    depends_on:
      - userrpc
      - entrpc
    ports:
      - "8092:8092"

networks:
  micro-mall:
