services:
  Etcd:
    platform: linux/x86_64 # m1 芯片需要设置 platform
    image: "bitnami/etcd:${ETCD_VERSION}"
    container_name: micro-etcd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    volumes:
      - ./etcd/data:/bitnami/etcd/data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - micro-svc

  postgres:
    image: postgres:latest
    container_name: micro-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - micro-svc-pg-data:/var/lib/postgresql/data
    networks:
      - micro-svc

  mysql8.2:
    platform: linux/x86_64 # m1 芯片需要设置 platform
    image: mysql:8.2.0
    container_name: micro-mysql
    restart: always
    networks:
      - micro-svc
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - micro-svc-mysql-data:/var/lib/mysql
      - ./mysql8.2/logs:/var/log/mysql
      - ./mysql8.2/conf/my.cnf:/etc/mysql/conf.d/my.cnf:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - "LANG=C.UTF-8"
      - TZ=Asia/Shanghai

  redis:
    image: redis:5.0
    restart: always
    container_name: micro-redis
    networks:
      - micro-svc
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - micro-svc-redis-data:/data:rw
      - ./redis5.0:/usr/local/etc/redis:rw
    environment:
      - "LANG=C.UTF-8"
      - TZ=Asia/Shanghai
      
  # jaeger链路追踪 — Jaeger for tracing
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    container_name: micro-jaeger
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
      - TZ=Asia/Shanghai
    depends_on:
      - elasticsearch
    networks:
      - micro-svc
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: micro-rabbitmq
    restart: always
    networks:
      - micro-svc
    ports:
      - "5672:5672"
      - "8081:15672"
    volumes:
      - micro-svc-rabbitmq-data:/var/lib/rabbitmq:rw
      - ./rabbitmq3/logs/:/var/log/rabbitmq
    environment:
      - "LANG=C.UTF-8"
      - TZ=Asia/Shanghai

networks:
  micro-svc:

volumes:
  micro-svc-pg-data:
  micro-svc-mysql-data:
  micro-svc-redis-data:
  micro-svc-rabbitmq-data:
