services:
  mysql8.2:
    platform: linux/x86_64 # m1 芯片需要设置 platform
    image: mysql:8.2.0
    container_name: micro-mysql
    restart: always
    networks:
      - micro-svc
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - micro-svc-mysql-data:/var/lib/mysql
      - ./mysql8.2/logs:/var/log/mysql
      - ./mysql8.2/conf/my.cnf:/etc/mysql/conf.d/my.cnf:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - "LANG=C.UTF-8"
      - TZ=Asia/Shanghai

networks:
  micro-svc:

volumes:
  micro-svc-mysql-data:
