version: "3.8"

services:
  Etcd:
    image: "bitnami/etcd:${ETCD_VERSION}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    volumes:
      - ./etcd/data:/bitnami/etcd/data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - micro-mall

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - micro-mall-pg-data:/var/lib/postgresql/data
    networks:
      - micro-mall

networks:
  micro-mall:

volumes:
  micro-mall-pg-data:
