filebeat.inputs:
  # 配置项目输入源，并区分access、error 日志

  #  ----------- (●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●) ------------
  # 【开发环境】
  # merchant 项目
  - type: log
    enabled: true
    paths:
      - /logs/dev/merchant_logs/access.log*
    fields:
      project: merchant
      log_type: access
      env: dev
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/dev/merchant_logs/error.log*
    fields:
      project: merchant
      log_type: error
      env: dev
    fields_under_root: true

  # store 项目
  - type: log
    enabled: true
    paths:
      - /logs/dev/store_logs/access.log*
    fields:
      project: store
      log_type: access
      env: dev
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/dev/store_logs/error.log*
    fields:
      project: store
      log_type: error
      env: dev
    fields_under_root: true

  # platform 项目
  - type: log
    enabled: true
    paths:
      - /logs/dev/platform_logs/access.log*
    fields:
      project: platform
      log_type: access
      env: dev
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/dev/platform_logs/error.log
    fields:
      project: platform
      log_type: error
      env: dev
    fields_under_root: true

  # scheduler 项目
  - type: log
    enabled: true
    paths:
      - /logs/dev/scheduler_logs/access.log*
    fields:
      project: scheduler
      log_type: access
      env: dev
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/dev/scheduler_logs/error.log
    fields:
      project: scheduler
      log_type: error
      env: dev
    fields_under_root: true

  #  ----------- (●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●)(●'◡'●) ------------
  # 【测试环境】
  # merchant 项目
  - type: log
    enabled: true
    paths:
      - /logs/test/merchant_logs/access.log*
    fields:
      project: merchant
      log_type: access
      env: test
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/test/merchant_logs/error.log*
    fields:
      project: merchant
      log_type: error
      env: test
    fields_under_root: true

  # store 项目
  - type: log
    enabled: true
    paths:
      - /logs/test/store_logs/access.log*
    fields:
      project: store
      log_type: access
      env: test
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/test/store_logs/error.log*
    fields:
      project: store
      log_type: error
      env: test
    fields_under_root: true

  # platform 项目
  - type: log
    enabled: true
    paths:
      - /logs/test/platform_logs/access.log*
    fields:
      project: platform
      log_type: access
      env: test
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/test/platform_logs/error.log
    fields:
      project: platform
      log_type: error
      env: test
    fields_under_root: true

  # scheduler 项目
  - type: log
    enabled: true
    paths:
      - /logs/test/scheduler_logs/access.log*
    fields:
      project: scheduler
      log_type: access
      env: test
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/test/scheduler_logs/error.log
    fields:
      project: scheduler
      log_type: error
      env: test
    fields_under_root: true

# 自动收集Docker的日志
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

# 日志处理器，用于在日志收集后进行进一步处理
processors:
  - add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"
